"""Update event table

Revision ID: c5c968f376e9
Revises: 125121663428
Create Date: 2025-11-04 22:41:38.205134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c968f376e9'
down_revision: Union[str, Sequence[str], None] = '125121663428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('events', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('founder_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('genre', sa.String(length=225), nullable=False))
    op.add_column('events', sa.Column('lat', sa.String(length=225), nullable=False))
    op.add_column('events', sa.Column('log', sa.String(length=225), nullable=False))
    op.add_column('events', sa.Column('start_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('events', sa.Column('end_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('events', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('description', sa.String(length=225), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_events_id', table_name='events')
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.drop_constraint('events_user_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['founder_id'], ['user_id'])
    op.drop_column('events', 'name')
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_user_id_fkey', 'events', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'description')
    op.drop_column('events', 'price')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'log')
    op.drop_column('events', 'lat')
    op.drop_column('events', 'genre')
    op.drop_column('events', 'founder_id')
    op.drop_column('events', 'title')
    op.drop_column('events', 'event_id')
    # ### end Alembic commands ###
